version: "3.8"

services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/main
    depends_on:
      - db

  frontend:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amare_Abewa12
      POSTGRES_DB: week7
    ports:
      - "2123:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
